name: Release

on:
  release:
    types: [created]

jobs:
  # Linux

  armv7-unknown-linux-gnueabihf:
    uses: ./.github/workflows/raspberry.yml
    with:
      target: armv7-unknown-linux-gnueabihf
      arch: armhf

  aarch64-unknown-linux-gnu:
    uses: ./.github/workflows/raspberry.yml
    with:
      target: aarch64-unknown-linux-gnu
      arch: arm64

  x86_64-unknown-linux-gnu:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: ubuntu-latest
      target: x86_64-unknown-linux-gnu

  x86_64-unknown-linux-musl:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: ubuntu-latest
      target: x86_64-unknown-linux-musl

  # macOS

  aarch64-apple-darwin:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: macos-latest
      target: aarch64-apple-darwin

  x86_64-apple-darwin:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: macos-latest
      target: x86_64-apple-darwin

  # Windows

  x86_64-pc-windows-gnu:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: windows-latest
      target: x86_64-pc-windows-gnu
      extension: .exe

  x86_64-pc-windows-msvc:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: windows-latest
      target: x86_64-pc-windows-msvc
      extension: .exe
